version: '3.7'
services:
  java_kit:
    container_name: java_kit
    build: .
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    environment:
      - DB_CONNECTION_URL=jdbc:postgresql://java_kit_db:5432/java_kit_db
      - DB_USERNAME=java_kit
      - DB_PASSWORD=java_kit
    depends_on:
      - java_kit_db
    ports:
      - 12128:12128
    networks:
      - java_kit
  java_kit_db:
    image: postgres:10.3
    container_name: java_kit_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=java_kit_db
      - POSTGRES_USER=java_kit
      - POSTGRES_PASSWORD=java_kit
    volumes:
      - java_kit_db:/var/lib/postgresql/data
    networks:
      - java_kit

networks:
  java_kit:

volumes:
  java_kit_db:
